### ISSUE TITLE
Ejercicio 1 A) 

### ISSUE THREAD

**Issue by Sofiortiz** [ISPC-TST-SENSORES-y-ACTUADORES-2023/tarea5-grupo-2#3]
Explique que es el Código Gray. ¿Cómo se utiliza en los Encoders 
Absolutos?

Subir respuesta en PDF en carpeta "6_Teoria" poner de nombre "A_Codigo_Grey.pdf"

**Comment by cande2323** [comment]
cumplimiento ejercicio 1 (A) codigo de gray #3
