### ISSUE TITLE
Ejercicio 1 B)

### ISSUE THREAD

**Issue by Sofiortiz** [ISPC-TST-SENSORES-y-ACTUADORES-2023/tarea5-grupo-2#4]
b) ¿Cómo implementaría un sensor inteligente de Posicionamiento Global?

Subir respuesta en PDF en carpeta "6_Teoria" poner de nombre "B_Sensor_Posicionamiento.pdf"

**Comment by joacorta** [comment]
complido ejercicio 1-B. sensor de posicionamiento. Con commit #12  commit 84aad676fe31a4a88b32a4312e32b1374b945e6e
