### ISSUE TITLE
Ejercicio 1 D)

### ISSUE THREAD

**Issue by Sofiortiz** [ISPC-TST-SENSORES-y-ACTUADORES-2023/tarea5-grupo-2#7]
d) Implementar y simular un circuito que funcione con fotodiodos. Simular con 
Wokwi, Proteus u otro software.(usando Arduino o ESP32, si fuera 
necesario)

Nota1: Visualizar las salidas en pantalla digital o Monitor serial del IDE ó VsCode

Subir archivo de simulacion en carpeta "Proyecto", codigo en carpeta "Software y los datasheet de sensores en "Hardware". PINOUT y bibliografia adicional en carpeta "Bibliografia"

Ver que hay subcarpeta de fotodiodos. Cargar ahi toda la info

**Comment by MrGuz2022** [comment]
Se realizo el ejercicio D , sobre circuito con fotodiodos
